apiVersion: v2
name: nginx-ingress
description: A simple wrapper around the stable/nginx-ingress chart that adds a few of our conventions
version: "0.2.0"
home: "https://github.com/norwoodj/helm-docs/tree/master/example-charts/nginx-ingress"
sources: ["https://github.com/norwoodj/helm-docs/tree/master/example-charts/nginx-ingress"]
engine: gotpl
type: application
maintainers:
  - email: norwood.john.m@gmail.com
    name: John Norwood
dependencies:
  - name: nginx-ingress
    version: "0.22.1"
    repository: "@stable"
